### 가중치를 구하는 문제이다.

### input
5
10 40 30 50 20
1 2 3 4 5

### output
32.0

### 수식은 선형 조합
수식 = sum(w * nums) / sum(w)

- 각 변수들을 순서대로 매칭해서 곱하면 된다.
- np.array로도 처리 가능할 것 같다.

In [2]:
n = int(input())
nums = list(map(int, input().split()))
w = list(map(int, input().split()))

w_sum = [i * j for i, j in zip(nums, w)]

print(round(sum(w_sum) / sum(w), 1))

5
10 40 30 50 20
1 2 3 4 5
32.0


### 넘파이로 풀기

In [6]:
ar_nums = np.array(nums)
ar_nums

array([10, 40, 30, 50, 20])

In [8]:
ar_w = np.array(w)
ar_w

array([1, 2, 3, 4, 5])

In [11]:
ar_lincomb = ar_w * ar_nums
ar_lincomb

array([ 10,  80,  90, 200, 100])

In [14]:
print(sum(ar_lincomb)/sum(ar_w))

32.0


### 더 디깅할 요소는 없는 듯

In [ ]:
# Python 3
def weighted_mean(numbers, weights):
    total = sum([num*weight for num,weight in zip(numbers,weights)])
    print(round(total / sum(weights),1))

numbers = int(input()) # Not needed; so overwrite var with next input
numbers = map(float, input().split())
weights = list(map(int, input().split()))

weighted_mean(numbers, weights)